name: Build, Scan, and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04

    steps:
      # Étape 1 : Vérifiez le code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Connectez-vous au registre GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Étape 3 : Build et taguez l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/ue19-lab-05:latest .

      # Étape 4 : Scannez l'image Docker avec Trivy et générez un rapport au format SARIF
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/ue19-lab-05:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'

      # Étape 5 : Téléversez les résultats du scan Trivy vers l'onglet Security de GitHub
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      # Étape 6 : Poussez l'image sur GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ue19-lab-05:latest
