name: Build, Scan, and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifiez le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Connectez-vous au registre GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Étape 3 : Build et taguez l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/ue19-lab-05:latest .

      # Étape 4 : Scannez l'image Docker avec Trivy
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.57.1
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/ue19-lab-05:latest
          format: table
          ignore-unfixed: true

      # Étape 5 : Poussez l'image sur GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ue19-lab-05:latest
