name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifiez le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Debug pour vérifier les variables
      - name: Debug repository owner
        run: echo "${{ github.repository_owner | toLower }}"

      # Étape 3 : Connectez-vous à GitHub Container Registry (ghcr.io)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Étape 4 : Build et taguez l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner | toLower }}/ue19-lab-05:latest .

      # Étape 5 : Poussez l'image sur GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner | toLower }}/ue19-lab-05:latest
